/**
 * Auto-generated fields for UserSubscribe
 * Generated at: 2026-05-16 11:50:19
 */
export const UserSubscribeFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 1, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'users',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "course_id", 
    label: "Course Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "course.name",
    required: 1, 
    placeholder: "Enter Course Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'courses',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "payment_method", 
    label: "Payment Method", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Payment Method",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "receipt_image", 
    label: "Receipt Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 0, 
    placeholder: "Enter Receipt Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "status", 
    label: "Status", 
    type: "select", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Status",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: "Pending", value: 'pending' }, { label: "Approved", value: 'approved' }, { label: "Rejected", value: 'rejected' }]
  },
  { 
    key: "admin_note", 
    label: "Admin Note", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Admin Note",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];